version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://priebe:ys2pAvp4OxIVJlyX@cluster0.eyermce.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=mytest
      - REDIS_URI=rediss://default:AVNS_NMUNeO_nOzHMVf_XSIJ@redis-7fefd97-bjarne-ddf3.aivencloud.com:11650
